### ISSUE TITLE
HTTP Error 403: Forbidden when downloading glue_tasks

### ISSUE THREAD

**Issue by huberemanuel** [microsoft/DeBERTa#14]
This error occurs when running the `setup_glue_data()` function inside any Glue Task script, like `qqp_large.sh`. 
The error resides on the original script `download_glue_data.py`, probably the token is no longer valid, but this directly affects this repo making it not possible to reproduce the results with the Glue Tasks.

Error log:
```bash
Downloading and extracting QQP...
Traceback (most recent call last):
  File "<stdin>", line 172, in <module>
  File "<stdin>", line 168, in main
  File "<stdin>", line 57, in download_and_extract
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bhadreshpsavani** [comment]
I am also facing the same error for QNLI task

**Comment by johnson7788** [comment]
I got the script, you can try:    https://github.com/johnson7788/DeBERTa/blob/master/utils/download_glue_data.py

**Comment by BigBird01** [comment]
This issue was fixed with the latest change. Could you take another try?

**Comment by deema-A** [comment]
Yes, I am having the same issue. 

> I got the script, you can try: https://github.com/johnson7788/DeBERTa/blob/master/utils/download_glue_data.py

Thank you that works with me!
