### ISSUE TITLE
assertion hit during forward pass

### ISSUE THREAD

**Issue by xzhu1900** [microsoft/DeBERTa#62]
Hi, 

I am trying out the DeBERTa model from the latest docker image provided. It seems like I hit an error during the forward pass: 

```
Downloading pytorch_model.bin: 100%|█| 1518990915/1518990915 [00:44<00:00, 33979
Downloading model_config.json: 100%|██████| 475/475 [00:00<00:00, 373718.70it/s]
07/24/2021 01:19:40|INFO|logging|00| Loaded pretrained model file /root/.~DeBERTa/assets/latest/deberta-xlarge/pytorch_model.bin
Traceback (most recent call last):
  File "model_copy.py", line 52, in <module>
    model = MyModel()
  File "model_copy.py", line 10, in __init__
    self.deberta = deberta.DeBERTa(pre_trained='xlarge') # Or 'large' 'base-mnli' 'large-mnli' 'xlarge' 'xlarge-mnli' 'xlarge-v2' 'xxlarge-v2'
  File "/usr/local/lib/python3.6/dist-packages/DeBERTa/deberta/deberta.py", line 57, in __init__
    self.apply_state(state)
  File "/usr/local/lib/python3.6/dist-packages/DeBERTa/deberta/deberta.py", line 147, in apply_state
    current[c] = state[key_match(c, state.keys())]
  File "/usr/local/lib/python3.6/dist-packages/DeBERTa/deberta/deberta.py", line 143, in key_match
    assert len(c)==1, c
AssertionError: []
```

The assertion shows there is one entry inside the dataset that doesn't have a key. I printed the keys it run into so far:

```
**  embeddings.word_embeddings.weight ['deberta.embeddings.word_embeddings.weight']
**  embeddings.LayerNorm.weight ['deberta.embeddings.LayerNorm.weight']
**  embeddings.LayerNorm.bias ['deberta.embeddings.LayerNorm.bias']
**  encoder.layer.0.attention.self.query_proj.weight []
```
The last entry didn't have a corresponding key. Is this expected? How should I work around it?

Thanks

**Comment by BigBird01** [comment]
The pip package is outdated.  You may install it from our source code.
