### ISSUE TITLE
How to train

### ISSUE THREAD

**Issue by GuoQuanhao** [microsoft/DeBERTa#63]
I use the following command
```python
python3 -m DeBERTa.apps.run --task_name $task --do_train  \
  --data_dir $cache_dir/glue_tasks/$task \
  --eval_batch_size 128 \
  --predict_batch_size 128 \
  --output_dir $OUTPUT \
  --scale_steps 250 \
  --loss_scale 16384 \
  --accumulative_update 1 \  
  --num_train_epochs 6 \
  --warmup 100 \
  --learning_rate 2e-5 \
  --train_batch_size 32 \
  --max_seq_len 128
```
But I got errors
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/DeBERTa/DeBERTa/DeBERTa/apps/run.py", line 449, in <module>
    main(args)
  File "/content/drive/MyDrive/DeBERTa/DeBERTa/DeBERTa/apps/run.py", line 268, in main
    tokenizer = tokenizers[vocab_type](vocab_path)
  File "/content/drive/MyDrive/DeBERTa/DeBERTa/DeBERTa/deberta/gpt2_tokenizer.py", line 61, in __init__
    self.gpt2_encoder = torch.load(vocab_file)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 235, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 220, in __init__
    _check_seekable(buffer)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 311, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 304, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
```
I found vocab_path is None, anyone can tell me how to set vocab_path

**Comment by BigBird01** [comment]
You missed the **--init_model $init** in the argument list.
Please check out our fine-tuning scripts for the usage.

**Comment by NIKHILDUGAR** [comment]
I was following these instructions. Can you send me the proper instructions.
